.TH MYSTRLEN 3 "2026" "libmyutils" "Library Functions Manual"
.SH NAME
mystrlen \- calculate the length of a string
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.sp
.BI "int mystrlen(const char *" s ");"
.SH DESCRIPTION
Returns the number of characters in the string
.I s
before the terminating null byte.
.SH AUTHOR
Zara Fatima <zara.alam285@gmail.com>
