.TH MYSTRCPY 3 "2026" "libmyutils" "Library Functions Manual"
.SH NAME
mystrcpy \- copy a string
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.sp
.BI "int mystrcpy(char *" dest ", const char *" src ");"
.SH DESCRIPTION
Copies the string pointed to by
.I src
into
.I dest,
including the terminating null byte. Returns the number of characters copied.
.SH AUTHOR
Zara Fatima <zara.alam285@gmail.com>
